### PR TITLE
Add a mirror for the model on a port 80 available server

### PR DESCRIPTION
**Pull request by kba**
thanks @VolkerHartmann

### CODE REVIEW

**Comment by mikegerber** [comment]
How will I be able to update this tar file? Before I cannot do this easily, I will not merge this.

**Comment by kba** [comment]
Feel free to close, I can always look up the URL in this then closed PR :)

**Comment by mikegerber** [comment]
I would gladly have this somewhere in the OCR-D repo, more accessible than on this 8443 port but I just have the need to do updates.

For example, I already trained a Calamari 1 model (still have to evaluate its performance) and I am training another one using augmentation. As soon as I update this script, the linked model will be obsolete.

**Comment by kba** [comment]
As I said: Totally get it, this was mostly because I needed a standard port to download from and kept forgetting the URL. Providing a model repository is an OCR-D task so hopefully we will reach some solution soon.

**Pull request closed without merging**
